name: Continuous Delivery Backend
on:
  push: # trigger the workflow once there is change pushed to main branch
    branches:
      - main
    paths:
      - backend/**
  workflow_dispatch: {} # Not sure what does this do, but let see the document later on

env:
  AWS_REGION: ap-southeast-1
  S3BUCKET: pcshopwebsite-artifacts
  TASK_DEFINITION_FAMILY: pcshop-api
  TASK_DEFINITION: pcshop-api:5
  SPRING_PROFILES_ACTIVE_KEY: SPRING_PROFILES_ACTIVE
  CONTAINER_NAME: pcshop-api
  CONTAINER_URL: stevenguyendev/pcshop-api
  CLUSTER_NAME: MyCluster
jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: # Read more https://docs.github.com/en/actions/deployment/environments
      name: Dev
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: stevenguyendev
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pcshop
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    permissions: # Read more https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: aws-actions/configure-aws-credentials@v2
        name: Configure AWS Credentials
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Build with Maven and push to Docker Hub
        run: mvn -ntp -B verify -Ddocker.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build
      - name: Update task definition with new tag then describe
        run: |
          aws ecs update-task-definition --family ${{ env.TASK_DEFINITION_FAMILY }} --task-definition ${{ env.TASK_DEFINITION }} --container-definitions '[{"name":"${{ env.CONTAINER_NAME }}","environment":[{"name":"${{ env.SPRING_PROFILES_ACTIVE_KEY }}","value":"dev"}]}]'
          aws ecs update-task-definition --family ${{ env.TASK_DEFINITION_FAMILY }} --task-definition ${{ env.TASK_DEFINITION }} --container-definitions '[{"name":"${{ env.CONTAINER_NAME }}","image":"${{ env.CONTAINER_URL }}: ${{ steps.build-number.outputs.BUILD_NUMBER }}"}]'
          aws ecs describe-task-definition --task-definition ${{ env.TASK_DEFINITION }} --query taskDefinition
      - name: Run task to deploy container to ECS
        run: |
          aws ecs run-task --cluster ${{ env.CLUSTER_NAME }} --task-definition ${{ env.TASK_DEFINITION }} --count 1