name: Continuous Integration Backend
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - backend/**
  workflow_dispatch: {}
jobs:
  build:
    name: Build and test pcshop backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: stevenguyendev
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pcshop
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-java@v3
        name: Set up JDK 17
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn compile -ntp
      - name: Run UT and IT tests with Maven
        run: mvn test -ntp
