name: Continuous integration frontend
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - frontend/**
  workflow_dispatch: {}
jobs:
  build:
    name: Build and test pcshop frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build
        run: npm build
      - name: Test
        run: npm test
