name: Continuous integration frontend
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - frontend/**
  workflow_dispatch: {}
jobs:
  build:
    name: Build and test pcshop frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
        # TODO: Add lint step
#      - name: Test
#        run: npm run test -- --no-watch --source-map=false --browsers=Chrome
